export type {
  BackendKind,
  FusedAttentionRequest,
  FusedAttentionResetOptions,
  FusedAttentionResult,
  FusedAttentionSession,
  InferenceBackend,
  MatrixRowRange,
  MatvecRequest,
  ResidentLayerRequest,
  ResidentTokenRequest,
  ResidentTokenSelection,
} from "./backends/backend.js";
export { NeedleError, type NeedleErrorCode } from "./errors.js";
export {
  CACT_HEADER_BYTES,
  CACT_RECORD_BYTES,
  CACT_TAG,
  CactDType,
  type CactEngramSite,
  type CactGeometry,
  type CactLayer,
  type CactProbeHead,
  type CactTensor,
  type CactTensorRecord,
  type CactWeights,
  type CqMatrix,
  type DenseTensor,
  parseCact,
  type RawTensor,
} from "./model/cact.js";
export {
  type BackendSelection,
  type GeneratedToken,
  type GenerateOptions,
  type GenerationResult,
  type LoadModelOptions,
  NeedleModel,
} from "./model/model.js";
export {
  NeedleRuntime,
  type RuntimeOptions,
  type RuntimeResetOptions,
} from "./model/runtime.js";
export {
  BOS_TOKEN_ID,
  CHAT_MARKERS,
  EOS_TOKEN_ID,
  NeedleTokenizer,
  PAD_TOKEN_ID,
  parseTokenizerMetadata,
  type TokenizerMetadata,
  TokenPieceType,
  UNKNOWN_TOKEN_ID,
} from "./model/tokenizer.js";
export {
  type CompleteOptions,
  type CompletionMetrics,
  createNeedle,
  type ExtractOptions,
  extract,
  Needle,
  type NeedleFunctionCall,
  type NeedleOptions,
  type NeedleResponse,
  type RunOptions,
} from "./tools/agent.js";
export {
  type GrammarToolCall,
  JsonSchemaGrammar,
  ToolCallGrammar,
} from "./tools/grammar.js";
export {
  type RetrieveToolsOptions,
  rankToolsBM25,
  retrieveTools,
} from "./tools/retrieval.js";
export {
  defineTool,
  type JsonPrimitive,
  type JsonSchema,
  type JsonValue,
  type NeedleTool,
  normalizeTool,
  normalizeTools,
  type OpenAIFunctionTool,
  type RawNeedleTool,
  serializeTools,
  type ToolExecutionContext,
  type ToolInput,
  tool,
} from "./tools/schema.js";
export {
  clearMemoryWeightCache,
  type EmbeddedWeightSource,
  type FileWeightSource,
  getEmbeddedWeights,
  hasEmbeddedWeights,
  type LoadWeightsOptions,
  loadWeights,
  NEEDLE_2_BYTES,
  NEEDLE_2_REPOSITORY,
  NEEDLE_2_REVISION,
  NEEDLE_2_SHA256,
  NEEDLE_2_URL,
  sha256,
  type UrlWeightSource,
  type WeightProgress,
  type WeightSource,
} from "./weights/source.js";
