#!/usr/bin/env bun
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { createHash } from "node:crypto";

const output = resolve(import.meta.dir, "../src/weights/embedded-model.ts");
const input = process.argv[2];

if (!input || input === "--help" || input === "-h") {
  console.log("Usage: bun run embed:model /path/to/needle2.cact\n       bun run embed:model --clear");
  process.exit(input ? 0 : 1);
}

if (input === "--clear") {
  await writeFile(output, `// Generated placeholder: no model is embedded.\nexport const embeddedModelBase64Chunks: readonly string[] | null = null;\nexport const embeddedModelSha256: string | null = null;\n`);
  console.log(`Cleared embedded model: ${output}`);
  process.exit(0);
}

const bytes = await readFile(resolve(input));
if (bytes.byteLength < 120 || bytes.readUInt32LE(0) !== 0x05e12a83) {
  throw new Error(`${input} is not a Needle .cact archive (missing 0x05e12a83 header tag)`);
}
const hash = createHash("sha256").update(bytes).digest("hex");
const chunkBytes = 192 * 1024; // divisible by three, so base64 chunks concatenate cleanly
const chunks: string[] = [];
for (let offset = 0; offset < bytes.byteLength; offset += chunkBytes) {
  chunks.push(bytes.subarray(offset, Math.min(offset + chunkBytes, bytes.byteLength)).toString("base64"));
}
const source = `// Generated by scripts/embed-model.ts. Do not hand-edit.\n` +
  `export const embeddedModelBase64Chunks: readonly string[] | null = [\n${chunks.map((chunk) => `  ${JSON.stringify(chunk)},`).join("\n")}\n];\n` +
  `export const embeddedModelSha256: string | null = ${JSON.stringify(hash)};\n`;
await mkdir(dirname(output), { recursive: true });
await writeFile(output, source);
console.log(`Embedded ${(bytes.byteLength / 1_000_000).toFixed(2)} MB in ${chunks.length} chunks`);
console.log(`SHA-256 ${hash}`);
console.log(output);
